<?php

namespace App\Dallas\Exports\DailyReport;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithMapping;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;

class TeacherStudentsExport implements FromArray, WithHeadings, WithTitle, WithStyles, WithColumnWidths, WithMapping
{
    protected array $data;
    protected array $teacher;
    protected array $students;
    protected string $selectedDate;
    protected string $selectedDay;

    public function __construct(array $data)
    {
        $this->data = $data;
        $this->teacher = $data['teacher'] ?? [];
        $this->students = $data['students'] ?? [];
        $this->selectedDate = $data['selected_date'] ?? date('Y-m-d');
        $this->selectedDay = $data['selected_day'] ?? date('l');
    }

    /**
     * Prepare the data array for export
     *
     * @return array
     */
    public function array(): array
    {
        $rows = [];

        // Add Header Information
        $rows[] = ['TEACHER STUDENT REPORT'];
        $rows[] = [];
        $rows[] = ['Teacher Information'];
        $rows[] = ['Teacher ID', $this->teacher['teacher_id'] ?? '-'];
        $rows[] = ['Custom ID', $this->teacher['custom_id'] ?? '-'];
        $rows[] = ['Teacher Name', $this->teacher['full_name'] ?? '-'];
        $rows[] = ['Initials', $this->teacher['initials'] ?? '-'];
        $rows[] = ['Email', $this->teacher['email'] ?? '-'];
        $rows[] = ['Mobile', $this->teacher['mobile'] ?? '-'];
        $rows[] = ['Joined Date', $this->teacher['joined_date'] ?? '-'];
        $rows[] = [];
        
        // Report Information
        $rows[] = ['Report Information'];
        $rows[] = ['Report Date', $this->selectedDate];
        $rows[] = ['Day', $this->selectedDay];
        $rows[] = ['Total Classes', $this->data['total_classes'] ?? 0];
        $rows[] = ['Total Students', $this->data['total_students'] ?? 0];
        $rows[] = ['Total Enrollments', $this->data['total_enrollments'] ?? 0];
        $rows[] = [];
        
        // Payment Summary
        if (isset($this->data['payment_summary'])) {
            $rows[] = ['Payment Summary'];
            $rows[] = ['Today\'s Payments', $this->data['payment_summary']['today']['total_payments'] ?? 0];
            $rows[] = ['Today\'s Amount', number_format($this->data['payment_summary']['today']['total_amount'] ?? 0, 2)];
            $rows[] = ['Monthly Payments', $this->data['payment_summary']['monthly']['total_payments'] ?? 0];
            $rows[] = ['Monthly Amount', number_format($this->data['payment_summary']['monthly']['total_amount'] ?? 0, 2)];
            $rows[] = ['Month', $this->data['payment_summary']['monthly']['month'] ?? '-'];
            $rows[] = [];
        }
        
        // Class Summary
        if (isset($this->data['class_summary']) && !empty($this->data['class_summary'])) {
            $rows[] = ['Class Summary'];
            $rows[] = ['Class Name', 'Grade', 'Student Count'];
            foreach ($this->data['class_summary'] as $class) {
                $rows[] = [
                    $class['class_name'] ?? '-',
                    $class['grade_name'] ?? '-',
                    $class['student_count'] ?? 0,
                ];
            }
            $rows[] = [];
        }
        
        // Students List Header
        $rows[] = ['STUDENTS LIST'];
        $rows[] = [];
        
        // The actual student data will be added by the WithMapping interface
        // But we need to add the data rows here
        foreach ($this->students as $student) {
            $rows[] = $this->map($student);
        }
        
        // Footer
        $rows[] = [];
        $rows[] = ['Report Generated On: ' . now()->format('d M Y, h:i A')];
        $rows[] = ['Generated By: ' . (auth()->user()->name ?? 'System')];
        
        return $rows;
    }

    /**
     * Map each student row
     *
     * @param array $student
     * @return array
     */
    public function map($student): array
    {
        return [
            $student['student_id'] ?? '-',
            $student['student_code'] ?? '-',
            $student['student_name'] ?? '-',
            $student['class_name'] ?? '-',
            $student['grade_name'] ?? '-',
            $student['guardian_mobile'] ?? '-',
            $student['student_mobile'] ?? '-',
            $student['student_email'] ?? '-',
            $student['payment_status'] ?? 'pending',
            number_format($student['balance'] ?? 0, 2),
            number_format($student['final_fee'] ?? 0, 2),
            $student['has_class_today'] ? 'Yes' : 'No',
            $student['class_day'] ?? '-',
            $student['last_payment'] ? date('d M Y', strtotime($student['last_payment']['paid_at'])) : 'No Payment',
            $student['last_payment'] ? number_format($student['last_payment']['amount'], 2) : '0.00',
            $student['last_payment']['receipt_number'] ?? '-',
        ];
    }

    /**
     * Excel headings for the main student table
     *
     * @return array
     */
    public function headings(): array
    {
        return [
            'Student ID',
            'Student Code',
            'Student Name',
            'Class Name',
            'Grade',
            'Guardian Mobile',
            'Student Mobile',
            'Email',
            'Payment Status',
            'Balance (Rs.)',
            'Final Fee (Rs.)',
            'Has Class Today',
            'Class Day',
            'Last Payment Date',
            'Last Payment Amount',
            'Receipt Number',
        ];
    }

    /**
     * Excel sheet title
     *
     * @return string
     */
    public function title(): string
    {
        $teacherName = $this->teacher['full_name'] ?? 'Teacher';
        return str_replace(' ', '_', substr($teacherName, 0, 25)) . '_Students';
    }

    /**
     * Apply styles to the worksheet
     *
     * @param Worksheet $sheet
     * @return array
     */
    public function styles(Worksheet $sheet): array
    {
        $lastRow = $sheet->getHighestRow();
        
        return [
            // Title row style (row 1)
            1 => [
                'font' => ['bold' => true, 'size' => 16, 'color' => ['rgb' => '2563eb']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            
            // Section headers (Teacher Information, Report Information, etc.)
            3 => ['font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '1e40af']]],
            11 => ['font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '1e40af']]],
            
            // Payment summary section
            isset($this->data['payment_summary']) ? 19 : null => ['font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '1e40af']]],
            
            // Class summary header
            isset($this->data['class_summary']) && !empty($this->data['class_summary']) ? 27 : null => ['font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '1e40af']]],
            
            // Students list header
            isset($this->data['class_summary']) && !empty($this->data['class_summary']) ? 31 : 27 => [
                'font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '1e40af']],
            ],
            
            // Table header row
            $this->getTableHeaderRow() => [
                'font' => ['bold' => true, 'size' => 11, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => [
                    'fillType' => Fill::FILL_SOLID,
                    'startColor' => ['rgb' => '2563eb'],
                ],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            
            // Footer style
            $lastRow => [
                'font' => ['italic' => true, 'size' => 9, 'color' => ['rgb' => '64748b']],
            ],
        ];
    }

    /**
     * Get the table header row number
     *
     * @return int
     */
    protected function getTableHeaderRow(): int
    {
        $baseRow = 27;
        
        if (isset($this->data['payment_summary'])) {
            $baseRow += 8;
        }
        
        if (isset($this->data['class_summary']) && !empty($this->data['class_summary'])) {
            $baseRow += 4 + count($this->data['class_summary']);
        }
        
        return $baseRow + 1;
    }

    /**
     * Set column widths
     *
     * @return array
     */
    public function columnWidths(): array
    {
        return [
            'A' => 12,  // Student ID
            'B' => 15,  // Student Code
            'C' => 25,  // Student Name
            'D' => 25,  // Class Name
            'E' => 12,  // Grade
            'F' => 18,  // Guardian Mobile
            'G' => 18,  // Student Mobile
            'H' => 30,  // Email
            'I' => 15,  // Payment Status
            'J' => 15,  // Balance
            'K' => 15,  // Final Fee
            'L' => 15,  // Has Class Today
            'M' => 15,  // Class Day
            'N' => 18,  // Last Payment Date
            'O' => 18,  // Last Payment Amount
            'P' => 20,  // Receipt Number
        ];
    }

    /**
     * Apply additional styling to the worksheet
     *
     * @param Worksheet $sheet
     */
    public function applyStyles(Worksheet $sheet): void
    {
        // Auto-size all columns
        foreach (range('A', 'P') as $column) {
            $sheet->getColumnDimension($column)->setAutoSize(false);
        }
        
        // Apply borders to the table
        $tableHeaderRow = $this->getTableHeaderRow();
        $lastRow = $sheet->getHighestRow();
        $lastColumn = 'P';
        
        // Apply borders to the data table
        $sheet->getStyle("A{$tableHeaderRow}:{$lastColumn}{$lastRow}")
            ->getBorders()
            ->getAllBorders()
            ->setBorderStyle(Border::BORDER_THIN)
            ->setColor(new Color('cbd5e1'));
        
        // Center align status column
        $sheet->getStyle("I{$tableHeaderRow}:I{$lastRow}")
            ->getAlignment()
            ->setHorizontal(Alignment::HORIZONTAL_CENTER);
        
        // Right align amount columns
        $amountColumns = ['J', 'K', 'O'];
        foreach ($amountColumns as $column) {
            $sheet->getStyle("{$column}{$tableHeaderRow}:{$column}{$lastRow}")
                ->getAlignment()
                ->setHorizontal(Alignment::HORIZONTAL_RIGHT);
        }
        
        // Highlight pending payments
        $statusColumn = 'I';
        for ($row = $tableHeaderRow + 1; $row <= $lastRow; $row++) {
            $status = $sheet->getCell("{$statusColumn}{$row}")->getValue();
            if ($status == 'pending') {
                $sheet->getStyle("A{$row}:{$lastColumn}{$row}")
                    ->getFill()
                    ->setFillType(Fill::FILL_SOLID)
                    ->setStartColor(new Color('fee2e2'));
            } elseif ($status == 'paid') {
                $sheet->getStyle("A{$row}:{$lastColumn}{$row}")
                    ->getFill()
                    ->setFillType(Fill::FILL_SOLID)
                    ->setStartColor(new Color('dcfce7'));
            } elseif ($status == 'partial') {
                $sheet->getStyle("A{$row}:{$lastColumn}{$row}")
                    ->getFill()
                    ->setFillType(Fill::FILL_SOLID)
                    ->setStartColor(new Color('fef3c7'));
            }
        }
    }
}